version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/onwords/
hooks:
  AfterInstall:
    - location: deploy/setup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/run.sh
      timeout: 300
      runas: root
